### ISSUE TITLE
Ingress values not applicable

### ISSUE THREAD

**Issue by timvtinsa** [perses/helm-charts#38]
### What did you do?

I tried to deploy Perses with the helm chart version 0.7.2 with the following `ingress` section in my `values.yaml`:
```
ingress:
  enabled: true
  hosts: 
    - host: _<my_host>_
      path: /
      pathType: ImplementationSpecific
  ingressClassName: "traefik"
```

### What did you expect to see?

I expected to see Perses deployed with my ingress resource created.

### What did you see instead? Under which circumstances?

A schema validation error:
```
STDERR:
  Error: values don't meet the specifications of the schema(s) in the following chart(s):
  perses:
  - ingress.hosts.0: Invalid type. Expected: string, given: object
```

The `ingress.hosts` is expecting a list of string but the `ingress.yaml` template contains:
```
rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
```
which suggests that the items in the `hosts` list must be objects, as specified in my values.

Moreover, the chart default values in `values.yaml` on the repository contains the following `ingress` section:
```
ingress:
  # -- Enable ingress controller resource
  enabled: false

  # -- Default host for the ingress resource
  hosts:
  - perses.local

  <...>
```
The `ingress.hosts` default value does not seem to match the ingress template in `ingress.yaml` (list of string VS list of objects).

### Perses version

```text
Helm chart version 0.7.2
```
