### ISSUE TITLE
Add Helm Chart Tests using bats-detik framework

### ISSUE THREAD

**Issue by ibakshay** [perses/helm-charts#39]
## Overview
Add comprehensive [Helm Chart Test](https://helm.sh/docs/topics/chart_tests/) capabilities to Perses helm charts using the [bats-detik testing framework](https://github.com/bats-core/bats-detik/tree/master).

## Motivation
Currently, Perses helm chart lack automated testing. Adding helm chart tests will improve reliability and catch potential issues earlier. 

## Proposed Solution
Implement helm chart tests using bats-detik framework, which offers several advantages:

1. Kubernetes-native testing capabilities with built-in assertions
2. Simple, human readible syntax for writing tests
3. Declarative test definitions using YAML
4. Built-in retry mechanisms for handling eventual consistency
5. Strong support for validating Kubernetes resources

## CI Integration
Will update GitHub Actions workflow to include helm testing:

```yaml
name: "Helm lint and tests"
jobs:
  helm-lint-test:
    runs-on: [ default ]
    steps:
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart integration tests
        run: ct install --config .github/configs/helm-test.yaml
```

## Prior Art
We're already successfully using bats-detik for the helm charts in our kubernetes-based platform. Reference implementation can be found here: https://cloudoperators.github.io/greenhouse/docs/user-guides/plugin/plugin-tests/

If this proposal is accepted then I will create a Pull Request 😀
CC: @nicolastakashi @Nexucis
